services:
#  app-demo:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
  grafana:
    build: './config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
            - grafana
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    user: "root"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      monitoring:
        aliases:
          - loki
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - nginx-proxy

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
            - prometheus
networks:
  monitoring: