scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.107:8081']
  - job_name: 'gps-guide-api'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'secret'
    static_configs:
      - targets: ['192.168.0.107:8080']